export const chineseQuestions = [
  {
    id: 1,
    question: '"合适" nghĩa là gì?',
    options: ["tương lai", "thuận tiện", "giải quyết", "phù hợp"],
    answer: "phù hợp",
  },
  {
    id: 2,
    question: '"空调" nghĩa là gì?',
    options: ["điều hòa", "kiên trì", "internet", "tiền thuê nhà"],
    answer: "điều hòa",
  },
  {
    id: 3,
    question: '"减少" nghĩa là gì?',
    options: ["thành công", "khán giả", "thử", "giảm bớt"],
    answer: "giảm bớt",
  },
  {
    id: 4,
    question: '"机会" nghĩa là gì?',
    options: ["máy giặt", "ngược lại", "nguy hiểm", "cơ hội"],
    answer: "cơ hội",
  },
  {
    id: 5,
    question: '"沙发" nghĩa là gì?',
    options: ["nâng cao", "thi đấu", "hồ", "sofa"],
    answer: "sofa",
  },
  {
    id: 6,
    question: '"文化" nghĩa là gì?',
    options: ["thi đấu", "tiền đặt cọc", "văn hóa", "hành lý"],
    answer: "văn hóa",
  },
  {
    id: 7,
    question: '"诚实" nghĩa là gì?',
    options: ["du lịch", "sofa", "cửa ra vào", "trung thực"],
    answer: "trung thực",
  },
  {
    id: 8,
    question: '"准时" nghĩa là gì?',
    options: ["đúng giờ", "đặc biệt", "giải quyết", "thành công"],
    answer: "đúng giờ",
  },
  {
    id: 9,
    question: '"讨论" nghĩa là gì?',
    options: ["máy giặt", "thuận tiện", "tương lai", "thảo luận"],
    answer: "thảo luận",
  },
  {
    id: 10,
    question: '"方便" nghĩa là gì?',
    options: ["thuận tiện", "thảo luận", "lịch sự", "bảo vệ"],
    answer: "thuận tiện",
  },
  {
    id: 11,
    question: '"相机" nghĩa là gì?',
    options: ["lãng phí", "hàng xóm", "máy ảnh", "phương pháp"],
    answer: "máy ảnh",
  },
  {
    id: 12,
    question: '"力量" nghĩa là gì?',
    options: ["tiền thuê nhà", "giải quyết", "sức mạnh", "phương pháp"],
    answer: "sức mạnh",
  },
  {
    id: 13,
    question: '"箱子" nghĩa là gì?',
    options: ["chăm sóc", "cố gắng", "thùng/hộp", "dọn dẹp"],
    answer: "thùng/hộp",
  },
  {
    id: 14,
    question: '"地图" nghĩa là gì?',
    options: ["hấp dẫn", "thất bại", "hiện đại", "bản đồ"],
    answer: "bản đồ",
  },
  {
    id: 15,
    question: '"方法" nghĩa là gì?',
    options: ["thành công", "lãng phí", "hấp dẫn", "phương pháp"],
    answer: "phương pháp",
  },
  {
    id: 16,
    question: '"押金" nghĩa là gì?',
    options: ["chuyển nhà", "chính xác", "lựa chọn", "tiền đặt cọc"],
    answer: "tiền đặt cọc",
  },
  {
    id: 17,
    question: '"安排" nghĩa là gì?',
    options: ["phát hiện", "sắp xếp", "hồ", "quần vợt"],
    answer: "sắp xếp",
  },
  {
    id: 18,
    question: '"门口" nghĩa là gì?',
    options: ["phù hợp", "phương pháp", "cửa ra vào", "mục tiêu"],
    answer: "cửa ra vào",
  },
  {
    id: 19,
    question: '"迷路" nghĩa là gì?',
    options: ["lãng phí", "kỳ lạ", "đi lạc", "phương pháp"],
    answer: "đi lạc",
  },
  {
    id: 20,
    question: '"习惯" nghĩa là gì?',
    options: ["tiến bộ", "bảo vệ", "lời khuyên", "thói quen"],
    answer: "thói quen",
  },
  {
    id: 21,
    question: '"理解" nghĩa là gì?',
    options: ["diễn viên", "hiểu, thông cảm", "bảo vệ", "khách du lịch"],
    answer: "hiểu, thông cảm",
  },
  {
    id: 22,
    question: '"桥" nghĩa là gì?',
    options: ["lựa chọn", "phát hiện", "sofa", "cây cầu"],
    answer: "cây cầu",
  },
  {
    id: 23,
    question: '"行李" nghĩa là gì?',
    options: ["nâng cao", "bảo tàng", "hành lý", "cơ hội"],
    answer: "hành lý",
  },
  {
    id: 24,
    question: '"精彩" nghĩa là gì?',
    options: ["hấp dẫn", "chương trình", "tụt lùi", "thuận tiện"],
    answer: "hấp dẫn",
  },
  {
    id: 25,
    question: '"纪念品" nghĩa là gì?',
    options: ["tủ lạnh", "quà lưu niệm", "diễn viên", "thi đấu"],
    answer: "quà lưu niệm",
  },
  {
    id: 26,
    question: "大家都在等你，快点儿，别让别人___太久。",
    options: ["搬", "寄", "等", "修"],
    answer: "等",
  },
  {
    id: 27,
    question: "请你先___一下名字和电话。",
    options: ["填写", "参观", "搬家", "鼓掌"],
    answer: "填写",
  },
  {
    id: 28,
    question: "这件事对我来说很___，我得认真考虑。",
    options: ["安静", "重要", "便宜", "拥挤"],
    answer: "重要",
  },
  {
    id: 29,
    question: "学习外语需要时间，也需要好___。",
    options: ["湖", "观众", "方法", "桥"],
    answer: "方法",
  },
  {
    id: 30,
    question: "他每次都___到学校，从不迟到。",
    options: ["平安", "热情", "安全", "准时"],
    answer: "准时",
  },
  {
    id: 31,
    question: "这家饭店的菜很___，很多人喜欢。",
    options: ["诚实", "准时", "新鲜", "勇敢"],
    answer: "新鲜",
  },
  {
    id: 32,
    question: "我想买一台新___来拍照。",
    options: ["相机", "空调", "电梯", "地图"],
    answer: "相机",
  },
  {
    id: 33,
    question: "他做事很___，从来不马虎。",
    options: ["热闹", "认真", "浪费", "普通"],
    answer: "认真",
  },
  {
    id: 34,
    question: "我们先买___，再进去参观。",
    options: ["门票", "押金", "网", "地址"],
    answer: "门票",
  },
  {
    id: 35,
    question: "这个房间很___，适合学习。",
    options: ["奇怪", "拥挤", "危险", "安静"],
    answer: "安静",
  },
  {
    id: 36,
    question: "这种运动不太___老人。",
    options: ["适合", "明白", "整理", "搬"],
    answer: "适合",
  },
  {
    id: 37,
    question: "看到老照片，我想起了很多___。",
    options: ["洗手间", "表格", "回忆", "电梯"],
    answer: "回忆",
  },
  {
    id: 38,
    question: "这个月___有点儿高，因为天天开空调。",
    options: ["方向", "电费", "节目", "礼物"],
    answer: "电费",
  },
  {
    id: 39,
    question: "地铁里人太多了，特别___。",
    options: ["合适", "简单", "拥挤", "安静"],
    answer: "拥挤",
  },
  {
    id: 40,
    question: "为了身体___，我决定每天跑步。",
    options: ["选择", "将来", "经验", "健康"],
    answer: "健康",
  },
  {
    id: 41,
    question: "大家都觉得这个办法很___。",
    options: ["吵", "合适", "严格", "拥挤"],
    answer: "合适",
  },
  {
    id: 42,
    question: "请不要___水，记得关好水龙头。",
    options: ["反对", "浪费", "讨论", "邀请"],
    answer: "浪费",
  },
  {
    id: 43,
    question: "如果遇到困难，不要轻易___。",
    options: ["参加", "保护", "放弃", "通知"],
    answer: "放弃",
  },
  {
    id: 44,
    question: "他第一次来中国，怕自己会___。",
    options: ["迷路", "习惯", "实现", "鼓掌"],
    answer: "迷路",
  },
  {
    id: 45,
    question: "这道题不太难，你再___一下。",
    options: ["租金", "搬家", "尝试", "保护"],
    answer: "尝试",
  },
  {
    id: 46,
    question: "你要先看清楚___再签字。",
    options: ["故事", "合同", "习惯", "照片"],
    answer: "合同",
  },
  {
    id: 47,
    question: "这个地方很___，坐地铁很方便。",
    options: ["近", "窄", "重", "远"],
    answer: "近",
  },
  {
    id: 48,
    question: "明天有考试，我今天晚上要好好___。",
    options: ["复习", "表演", "洗澡", "旅游"],
    answer: "复习",
  },
  {
    id: 49,
    question: "老师让我把这些书___一下。",
    options: ["整理", "旅行", "表扬", "理解"],
    answer: "整理",
  },
  {
    id: 50,
    question: "出国以前要先准备好___。",
    options: ["护照", "押金", "冰箱", "网球"],
    answer: "护照",
  },
  {
    id: 51,
    question: "A: 你怎么知道这个消息的？\nB: ___",
    options: [
      "刚才我的朋友告诉。",
      "朋友告诉我的刚才。",
      "告诉我的朋友刚才吗。",
      "朋友刚才告诉我的。",
    ],
    answer: "朋友刚才告诉我的。",
  },
  {
    id: 52,
    question: "A: 你的目标是什么？\nB: ___",
    options: [
      "是我的目标提高水平汉语。",
      "我的目标是提高汉语水平。",
      "我的汉语目标提高是水平。",
      "目标我的提高汉语水平。",
    ],
    answer: "我的目标是提高汉语水平。",
  },
  {
    id: 53,
    question: "A: 你需要我帮忙吗？\nB: ___",
    options: [
      "谢谢需要你。",
      "需要，谢谢你。",
      "需要你谢谢吗。",
      "你谢谢需要。",
    ],
    answer: "需要，谢谢你。",
  },
  {
    id: 54,
    question: "A: 明天谁来安排活动？\nB: ___",
    options: [
      "来安排王老师吗。",
      "王老师来安排。",
      "王老师安排来。",
      "安排来王老师。",
    ],
    answer: "王老师来安排。",
  },
  {
    id: 55,
    question: "A: 你觉得上海怎么样？\nB: ___",
    options: [
      "很现代，也很方便。",
      "现代很，也方便很。",
      "也很现代，方便很。",
      "很方便，也很现代吗。",
    ],
    answer: "很现代，也很方便。",
  },
  {
    id: 56,
    question: "A: 你会继续学下去吗？\nB: ___",
    options: [
      "会，我不会过程。",
      "会，我不会邻居。",
      "会，我不会放弃。",
      "会，我不会结果。",
    ],
    answer: "会，我不会放弃。",
  },
  {
    id: 57,
    question: "A: 你为什么买这个相机？\nB: ___",
    options: [
      "因为我拍照喜欢吗。",
      "因为拍照我喜欢很。",
      "因为喜欢我拍照。",
      "因为我喜欢拍照。",
    ],
    answer: "因为我喜欢拍照。",
  },
  {
    id: 58,
    question: "A: 你为什么不进去？\nB: ___",
    options: [
      "因为我忘带钥匙了。",
      "因为我钥匙带忘了。",
      "因为我忘了钥匙带。",
      "因为钥匙我忘了带吗。",
    ],
    answer: "因为我忘带钥匙了。",
  },
  {
    id: 59,
    question: "A: 你找得到路吗？\nB: ___",
    options: [
      "不一定，我怕门票。",
      "不一定，我怕地图。",
      "不一定，我怕方向。",
      "不一定，我怕迷路。",
    ],
    answer: "不一定，我怕迷路。",
  },
  {
    id: 60,
    question: "A: 你周末有什么计划？\nB: ___",
    options: [
      "我在计划博物馆。",
      "博物馆计划我很。",
      "我计划很博物馆。",
      "我想去博物馆看看。",
    ],
    answer: "我想去博物馆看看。",
  },
  {
    id: 61,
    question: "A: 这家饭店怎么样？\nB: ___",
    options: [
      "菜很热情，服务员也新鲜。",
      "热情菜很，服务员也新鲜。",
      "菜很新鲜，服务员也很热情。",
      "服务员新鲜也很热情菜。",
    ],
    answer: "菜很新鲜，服务员也很热情。",
  },
  {
    id: 62,
    question: "A: 你为什么这么累？\nB: ___",
    options: [
      "因为我昨天很押金。",
      "因为我昨天很合同。",
      "因为我昨天搬家了。",
      "因为我昨天很角落。",
    ],
    answer: "因为我昨天搬家了。",
  },
  {
    id: 63,
    question: "A: 这个答案对吗？\nB: ___",
    options: [
      "我准确觉得很。",
      "准确我觉得吗很。",
      "我觉得很准确。",
      "很觉得我准确。",
    ],
    answer: "我觉得很准确。",
  },
  {
    id: 64,
    question: "A: 你觉得这个办法怎么样？\nB: ___",
    options: [
      "我觉得还可以。",
      "我还可以觉得。",
      "觉得我还可以吗。",
      "还可以我觉得吗。",
    ],
    answer: "我觉得还可以。",
  },
  {
    id: 65,
    question: "A: 你为什么不开心？\nB: ___",
    options: [
      "因为我的考试成绩不太好。",
      "因为考试我的不太好成绩。",
      "因为我的成绩考试不太好。",
      "因为不太好我的考试成绩。",
    ],
    answer: "因为我的考试成绩不太好。",
  },
  {
    id: 66,
    question: "A: 为什么这么多人？\nB: ___",
    options: [
      "因为今天节目很一个精彩。",
      "因为今天有一个很精彩的节目。",
      "因为今天很节目精彩一个。",
      "因为一个精彩今天很节目。",
    ],
    answer: "因为今天有一个很精彩的节目。",
  },
  {
    id: 67,
    question: "A: 你的新家怎么样？\nB: ___",
    options: [
      "友好也邻居挺不错。",
      "挺友好不错邻居也。",
      "挺不错的，邻居也很友好。",
      "邻居不错也挺友好。",
    ],
    answer: "挺不错的，邻居也很友好。",
  },
  {
    id: 68,
    question: "A: 你打算什么时候出发？\nB: ___",
    options: [
      "我想明天一早出发。",
      "我想出发明天一早。",
      "出发我想一早明天。",
      "明天一早出发我想吗。",
    ],
    answer: "我想明天一早出发。",
  },
  {
    id: 69,
    question: "A: 你认识楼下的人吗？\nB: ___",
    options: [
      "他们一点儿认识是我的邻居。",
      "认识一点儿，他们是我的邻居。",
      "认识他们我的邻居一点儿。",
      "邻居是他们我的认识一点儿。",
    ],
    answer: "认识一点儿，他们是我的邻居。",
  },
  {
    id: 70,
    question: "A: 这个地方远吗？\nB: ___",
    options: [
      "坐车二十分钟不太远吗。",
      "二十分钟不太远坐车。",
      "不太远，坐车二十分钟。",
      "不太坐车远二十分钟。",
    ],
    answer: "不太远，坐车二十分钟。",
  },
  {
    id: 71,
    question: "A: 你为什么这么高兴？\nB: ___",
    options: [
      "因为我很箱子。",
      "因为我很方向。",
      "因为我很押金。",
      "因为我终于考好了。",
    ],
    answer: "因为我终于考好了。",
  },
  {
    id: 72,
    question: "A: 今天天气怎么样？\nB: ___",
    options: [
      "不过有点儿空气冷很好。",
      "有点儿很好不过冷空气。",
      "有点儿冷，不过空气很好。",
      "空气不过有点儿冷很好。",
    ],
    answer: "有点儿冷，不过空气很好。",
  },
  {
    id: 73,
    question: "A: 这次比赛你为什么赢了？\nB: ___",
    options: [
      "因为我准备得很认真。",
      "因为准备得我很认真吗。",
      "因为我认真很准备得。",
      "因为很认真我准备得。",
    ],
    answer: "因为我准备得很认真。",
  },
  {
    id: 74,
    question: "A: 你周末去哪里？\nB: ___",
    options: [
      "去湖边我想走走吗。",
      "我想去湖边走走。",
      "湖边走走我想去很。",
      "我想湖边去走走。",
    ],
    answer: "我想去湖边走走。",
  },
  {
    id: 75,
    question: "A: 这个地方怎么样？\nB: ___",
    options: [
      "很学习，适合安静。",
      "很安静，适合学习。",
      "适合安静很学习。",
      "安静很学习适合。",
    ],
    answer: "很安静，适合学习。",
  },
  {
    id: 76,
    question: "Câu nào đúng?",
    options: [
      "王老师安排已经好了。",
      "已经王老师安排好了。",
      "好了王老师已经安排。",
      "王老师已经安排好了。",
    ],
    answer: "王老师已经安排好了。",
  },
  {
    id: 77,
    question: "Câu nào đúng?",
    options: [
      "学习他每天都认真。",
      "每天他都认真学习。",
      "他每天都认真学习。",
      "他认真每天都学习。",
    ],
    answer: "他每天都认真学习。",
  },
  {
    id: 78,
    question: "Câu nào đúng?",
    options: [
      "买票我先想去。",
      "我先想去买票。",
      "去买票我想先。",
      "我想先去买票。",
    ],
    answer: "我想先去买票。",
  },
  {
    id: 79,
    question: "Câu nào đúng?",
    options: [
      "已经我做完作业了。",
      "我已经做完作业了。",
      "我做完已经作业了。",
      "作业了我已经做完。",
    ],
    answer: "我已经做完作业了。",
  },
  {
    id: 80,
    question: "Câu nào đúng?",
    options: [
      "我怕没有地图会迷路。",
      "我怕会迷路没有地图。",
      "迷路我怕没有地图会。",
      "没有地图我怕会迷路。",
    ],
    answer: "我怕没有地图会迷路。",
  },
  {
    id: 81,
    question: "Câu nào đúng?",
    options: [
      "很满意我对这个结果。",
      "对这个结果我很满意。",
      "我很满意对这个结果。",
      "我对这个结果很满意。",
    ],
    answer: "我对这个结果很满意。",
  },
  {
    id: 82,
    question: "Câu nào đúng?",
    options: [
      "当医生我将来想。",
      "我想将来当医生。",
      "我将来想当医生。",
      "将来我想当医生。",
    ],
    answer: "我将来想当医生。",
  },
  {
    id: 83,
    question: "Câu nào đúng?",
    options: [
      "大声说话图书馆里禁止。",
      "图书馆里禁止大声说话。",
      "禁止图书馆里大声说话。",
      "图书馆里大声说话禁止。",
    ],
    answer: "图书馆里禁止大声说话。",
  },
  {
    id: 84,
    question: "Câu nào đúng?",
    options: [
      "景点里很多有游客。",
      "很多游客景点里有。",
      "景点里有很多游客。",
      "游客景点里有很多。",
    ],
    answer: "景点里有很多游客。",
  },
  {
    id: 85,
    question: "Câu nào đúng?",
    options: [
      "不但她会唱歌，还会跳舞。",
      "她不但会唱歌，还会跳舞。",
      "还会跳舞她不但会唱歌。",
      "她会唱歌不但，还会跳舞。",
    ],
    answer: "她不但会唱歌，还会跳舞。",
  },
  {
    id: 86,
    question: "Câu nào đúng?",
    options: [
      "因为下雨，所以我们没去。",
      "因为下雨，我们所以没去。",
      "所以下雨，因为我们没去。",
      "我们没去因为所以下雨。",
    ],
    answer: "因为下雨，所以我们没去。",
  },
  {
    id: 87,
    question: "Câu nào đúng?",
    options: [
      "我们先看看情况吧。",
      "先看看我们情况吧。",
      "我们看看先情况吧。",
      "情况吧我们先看看。",
    ],
    answer: "我们先看看情况吧。",
  },
  {
    id: 88,
    question: "Câu nào đúng?",
    options: [
      "去博物馆我们明天一起。",
      "我们明天一起去博物馆。",
      "我们一起明天去博物馆。",
      "明天我们一起去博物馆。",
    ],
    answer: "我们明天一起去博物馆。",
  },
  {
    id: 89,
    question: "Câu nào đúng?",
    options: [
      "我最近很大有进步。",
      "进步我最近有很大。",
      "我最近有很大进步。",
      "很大进步我最近有。",
    ],
    answer: "我最近有很大进步。",
  },
  {
    id: 90,
    question: "Câu nào đúng?",
    options: [
      "如果没有钥匙，进不去就。",
      "如果没有钥匙，就进不去。",
      "就进不去如果没有钥匙。",
      "进不去如果没有钥匙就。",
    ],
    answer: "如果没有钥匙，就进不去。",
  },
  {
    id: 91,
    question: "Câu nào đúng?",
    options: [
      "我希望将来生活更好。",
      "将来我希望生活更好。",
      "生活更好我希望将来。",
      "我将来希望生活更好。",
    ],
    answer: "我希望将来生活更好。",
  },
  {
    id: 92,
    question: "Câu nào đúng?",
    options: [
      "很新鲜山上的空气。",
      "山上的空气很新鲜。",
      "空气山上的很新鲜。",
      "山上空气的很新鲜。",
    ],
    answer: "山上的空气很新鲜。",
  },
  {
    id: 93,
    question: "Câu nào đúng?",
    options: [
      "他都很有礼貌对大家。",
      "他对大家都很有礼貌。",
      "对大家他都很有礼貌。",
      "很有礼貌他对大家都。",
    ],
    answer: "他对大家都很有礼貌。",
  },
  {
    id: 94,
    question: "Câu nào đúng?",
    options: [
      "适合这件衣服你很。",
      "这件衣服你很适合。",
      "很适合你这件衣服。",
      "这件衣服很适合你。",
    ],
    answer: "这件衣服很适合你。",
  },
  {
    id: 95,
    question: "Câu nào đúng?",
    options: [
      "比赛这次非常精彩。",
      "非常精彩这次比赛。",
      "这次非常精彩比赛。",
      "这次比赛非常精彩。",
    ],
    answer: "这次比赛非常精彩。",
  },
  {
    id: 96,
    question: "Câu nào đúng?",
    options: [
      "环境我们应该保护吗。",
      "我们应该保护环境。",
      "我们环境应该保护。",
      "保护我们应该环境。",
    ],
    answer: "我们应该保护环境。",
  },
  {
    id: 97,
    question: "Câu nào đúng?",
    options: [
      "这个方法很有用。",
      "这个很有用方法。",
      "方法这个很有用。",
      "很有用这个方法。",
    ],
    answer: "这个方法很有用。",
  },
  {
    id: 98,
    question: "Câu nào đúng?",
    options: [
      "比以前这个地方热闹多了。",
      "热闹多了这个地方比以前。",
      "这个地方热闹比以前多了。",
      "这个地方比以前热闹多了。",
    ],
    answer: "这个地方比以前热闹多了。",
  },
  {
    id: 99,
    question: "Câu nào đúng?",
    options: [
      "这里晚上不太安全。",
      "这里不太晚上安全。",
      "晚上这里不太安全。",
      "不太安全这里晚上。",
    ],
    answer: "这里晚上不太安全。",
  },
  {
    id: 100,
    question: "Câu nào đúng?",
    options: [
      "很热情她对每个人都。",
      "她对每个人都很热情。",
      "她都很热情对每个人。",
      "对每个人她都很热情。",
    ],
    answer: "她对每个人都很热情。",
  },
];
